/* eslint-disable react/display-name */
/* eslint-disable import/prefer-default-export */
import React from 'react';
import {
  Box,
  Flex,
  SimpleGrid,
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionPanel,
  AccordionIcon,
  Heading,
  Text,
  Link,
  Icon,
  Image,
  Wrap,
  WrapItem,
  Stack,
  StackItem,
  HStack,
  VStack,
  Button,
  Checkbox,
  FormControl,
  IconButton,
  Input,
  NumberInput,
  Radio,
  Select,
  Slider,
  Switch,
  Textarea,
  Badge,
  Kbd,
  Tag,
  TagLabel,
  TagLeftIcon,
  TagRightIcon,
  TagCloseButton,
  Skeleton,
  SkeletonCircle,
  SkeletonText,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  Divider,
  UnorderedList,
  OrderedList,
  ListItem,
  Code,
} from '@chakra-ui/react';

const ChakraUIComponents = {
  Box,
  Flex,
  SimpleGrid,
  Accordion,
  AccordionItem,
  AccordionButton,
  AccordionPanel,
  AccordionIcon,
  Heading,
  Text,
  Link,
  Icon,
  Image,
  Wrap,
  WrapItem,
  Stack,
  StackItem,
  HStack,
  VStack,
  Button,
  Checkbox,
  FormControl,
  IconButton,
  Input,
  NumberInput,
  Radio,
  Select,
  Slider,
  Switch,
  Textarea,
  Badge,
  Kbd,
  Tag,
  TagLabel,
  TagLeftIcon,
  TagRightIcon,
  TagCloseButton,
  Skeleton,
  SkeletonCircle,
  SkeletonText,
  Tabs,
  TabList,
  TabPanels,
  Tab,
  TabPanel,
  Divider,
  UnorderedList,
  OrderedList,
  ListItem,
  Code,
};

export const UIComponents = {
  h1: (props) => <Heading as="h1" size="2xl" {...props} />,
  h2: (props) => <Heading as="h2" size="xl" {...props} />,
  h3: (props) => <Heading as="h3" size="lg" {...props} />,
  h4: (props) => <Heading as="h4" size="md" {...props} />,
  h5: (props) => <Heading as="h5" size="sm" {...props} />,
  h6: (props) => <Heading as="h6" size="xs" {...props} />,
  p: (props) => <Text as="p" {...props} />,
  hr: (props) => <Divider {...props} />,
  ul: (props) => <UnorderedList {...props} />,
  ol: (props) => <OrderedList {...props} />,
  li: (props) => <ListItem {...props} />,
  pre: (props) => <Code {...props} />,
  // code: CodeBlock,
  ...ChakraUIComponents,
};
